# Generated by Django 4.1 on 2023-05-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='イベント名')),
                ('event_id', models.IntegerField(verbose_name='イベントID')),
                ('start_dt', models.DateTimeField(verbose_name='開始日時')),
                ('end_dt', models.DateTimeField(verbose_name='終了日時')),
                ('schedule', models.JSONField(default=list, verbose_name='スケジュール')),
                ('remark', models.TextField(verbose_name='備考')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
            ],
            options={
                'verbose_name': 'SRイベント',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ルーム名')),
                ('room_id', models.IntegerField(verbose_name='ルームID')),
                ('point', models.JSONField(default=list, verbose_name='ポイント')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.srevent', verbose_name='SRイベント')),
            ],
            options={
                'verbose_name': 'ルーム',
            },
        ),
    ]
