# Generated by Django 4.1 on 2023-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srevent',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='srevent',
            name='schedule',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='スケジュール'),
        ),
    ]
