# Generated by Django 4.1 on 2023-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_room_room_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='point',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ポイント'),
        ),
    ]
