# Generated by Django 4.1 on 2023-05-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_alter_room_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'ルーム', 'verbose_name_plural': 'ルーム一覧'},
        ),
        migrations.AlterModelOptions(
            name='srevent',
            options={'verbose_name': 'SRイベント', 'verbose_name_plural': 'SRイベント一覧'},
        ),
        migrations.AlterField(
            model_name='room',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='graph.srevent', verbose_name='SRイベント'),
        ),
    ]
