# Generated by Django 4.1 on 2023-05-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_alter_room_options_alter_srevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srevent',
            name='last_watch_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終観測日時'),
        ),
    ]
