# Generated by Django 4.1 on 2023-08-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_srevent_last_watch_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srevent',
            name='event_id',
            field=models.IntegerField(unique=True, verbose_name='イベントID'),
        ),
    ]
